### ISSUE TITLE
Bottom overlflow on Linux (desktop)

### ISSUE THREAD

**Issue by giaur500** [AbdelbakiBoukerche/ABRibbon#1]
On desktop (Linux) I am getting this:

![image](https://user-images.githubusercontent.com/26817206/121775341-40049e00-cb87-11eb-8da4-0ebad8e1f0f4.png)

All is fine on web, any idea? BTW excellent project, it looks very good.

**Comment by AbdelbakiBoukerche** [comment]
Hi, thank for trying ABRibbon. As for your problem:

Because screens come in different size, I've provided some properties that you can set base on your different windows sizes. **_itemBarHeight_** is responsible for the height, it's set to **_100.0 by default_** but you can pass any value you want!
``` dart
ABRibbon({
    Key? key,
    this.tabHeight = 62.0,
    this.itemBarHeight = 100.0,
    this.width = double.infinity,
    this.elevation = 1.0,
    required this.primaryColor,
    required this.secondaryColor,
    required this.ribbonTabs,
    required this.tabsCount,
    required this.ribbonTabItems,
  })   : assert(ribbonTabItems.length == tabsCount),
        super(key: key);
```
You can use itemBarHeight

**Comment by giaur500** [comment]
Ok, but better to auto size bar to fit content height
